# Generated by Django 2.1 on 2019-05-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20190502_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=50, verbose_name='목록 이름'),
        ),
    ]
