# Generated by Django 2.1.5 on 2019-04-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deadline_date',
            field=models.DateField(blank=True),
        ),
    ]
