# Generated by Django 2.1 on 2019-04-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmanagement', '0002_auto_20190424_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
