# Generated by Django 2.1.5 on 2019-04-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmanagement', '0004_activity_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
