# Generated by Django 2.1.5 on 2019-04-26 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workmanagement', '0005_auto_20190426_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deadline_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
